// Copyright (c) 2018 Cloudera, Inc. All rights reserved.
package com.cloudera.ipe;

/**
 * This enum is used by the analysis rules to assign the type of data that is
 * generated by the different metrics of each rule.
 */
public enum AttributeDataType {
  STRING,
  NUMBER,
  BOOLEAN,
  BYTES,
  MILLISECONDS,
  BYTES_PER_SECOND,
  BYTE_SECONDS
}
